[tox]
envlist =
  py{310,311,312}-dj{5115,52}
  py312-djmain
  docs

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312

[gh-actions:env]
DJANGO =
    5.1.15: dj5115
    5.2.x: dj52
    main: djmain

[testenv]
basepython =
  py310: python3.10
  py311: python3.11
  py312: python3.12
deps =
  dj5115: Django==5.1.15
  dj52: Django>=5.2,<5.3
  djmain: https://github.com/django/django/archive/main.tar.gz
  jinja2
  coverage
  jsmin==3.0.0
  ply==3.4
  css-html-js-minify==2.5.5
setenv =
    DJANGO_SETTINGS_MODULE = tests.settings
    PYTHONPATH = {toxinidir}
commands =
    npm install
    {envbindir}/coverage run --source pipeline {envbindir}/django-admin test {posargs:tests}
    {envbindir}/coverage report
    {envbindir}/coverage xml
allowlist_externals = npm
ignore_outcome =
    djmain: True

[testenv:docs]
basepython = python3.11
changedir = docs
deps = sphinx
commands =
    {envbindir}/sphinx-build -W -b html -d {envtmpdir}/doctrees . {envtmpdir}/html
